# Generated by Django 4.2.19 on 2025-02-19 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Foto', models.ImageField(upload_to='foto/')),
                ('Nome:', models.CharField(max_length=100)),
                ('CPF.:', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='ATENÇÃO: CPF Inválido.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-d{2}$')])),
                ('Data de Nascimento:', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ATENÇÃO: Data de Nascimento inválida!', regex='^\\d{2}/\\d{2}/\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.FileField(upload_to='treinamento/')),
            ],
            options={
                'verbose_name': 'Treinamentos',
            },
        ),
        migrations.CreateModel(
            name='ColetaFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roi/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_coletas', to='registro.funcionario')),
            ],
        ),
    ]
